name: Build and Deploy LLM Runtime Container

on:
  workflow_dispatch

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch AWS Credentials
        run: echo "TODO"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd runtime_container/ && \
          pip install -r requirements.txt && \
          pip install -r requirements_torch_cpu.txt

      - name: Download Model
        run: |
          cd runtime_container/opt-350m && \
          git lfs install && \
          git clone https://huggingface.co/facebook/opt-350m && \
          mv opt-350m/* .

      - name: Quantize Model
        run: |
          cd runtime_container/ && \
          optimum-cli export openvino --model opt-350m/ \
                                      --cache_dir opt-350m-ov/model_cache/ \
                                      --task text-generation \
                                      --int8 \
                                      opt-350m-ov/

      - name: Build Runtime Container
        run: |
          cd runtime_container/ && \
          docker build \
            --build-arg LLM_FORBIDDEN_WORDS="${{secrets.LLM_FORBIDDEN_WORDS}}" \
            --build-arg REDIS_HOST="${{secrets.REDIS_HOST}}" \
            -t opt-350m-openvino-int8 \
            .

      - name: Push to ECR
        run: echo "TODO"
